Repository knative/caching, pull requests merged in 2019-05, with the labels that each got.

#29 Update test-infra: some fixes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#30 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#31 Update test-infra: get rid of Unbound variable running update-deps wa…
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#32 Update OWNERS to use OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, lgtm, size/M

#33 Remove unnecessary caching-reviewers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
