Repository knative/caching, pull requests merged in 2019-07, with the labels that each got.

#42 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/limitrange.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go
Labels: approved, lgtm, ok-to-test, size/L

#43 Stop printing images.caching.internal.knative.dev resource in kubectl get all
  config/image.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#45 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
Labels: approved, lgtm, ok-to-test, size/M

#44 Upgrade kubernetes-1.12.6 -> kubernetes-1.12.9
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/client-go/discovery/cached_discovery.go
  vendor/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/client-go/rest/transport.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
Labels: approved, lgtm, size/M

#48 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#49 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/user_info.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/M

#50 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/volatile_time.go
Labels: approved, lgtm, ok-to-test, size/XS

#56 Update pkg and opencensus dep.
  Gopkg.lock
  Gopkg.toml
  vendor/contrib.go.opencensus.io/exporter/prometheus/LICENSE
  vendor/contrib.go.opencensus.io/exporter/prometheus/prometheus.go
  vendor/contrib.go.opencensus.io/exporter/prometheus/sanitize.go
  vendor/go.opencensus.io/exporter/prometheus/prometheus.go
  vendor/go.opencensus.io/metric/metricdata/exemplar.go
  vendor/go.opencensus.io/metric/metricdata/label.go
  vendor/go.opencensus.io/metric/metricdata/metric.go
  vendor/go.opencensus.io/metric/metricexport/doc.go
  vendor/go.opencensus.io/metric/metricexport/export.go
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/tag/key.go
  vendor/go.opencensus.io/tag/map.go
  vendor/go.opencensus.io/tag/map_codec.go
  vendor/go.opencensus.io/tag/metadata.go
  vendor/go.opencensus.io/tag/profile_19.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/tracing/opencensus.go
Labels: approved, lgtm, size/XXL

#57 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
Labels: approved, lgtm, ok-to-test, size/M

#58 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/ptr/ptr.go
Labels: approved, lgtm, ok-to-test, size/L

#59 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/cloudevents/event.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#60 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/metadata_validation.go
  vendor/knative.dev/pkg/webhook/user_info.go
Labels: approved, lgtm, ok-to-test, size/M

#61 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/knative.dev/pkg/configmap/store.go
Labels: approved, lgtm, ok-to-test, size/S

#63 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, lgtm, ok-to-test, size/S
