Repository knative/caching, pull requests merged in 2020-02, with the labels that each got.

#194 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/.gitignore
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, lgtm, size/L

#195 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/main.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/types.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/testing/factory.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#196 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/namesystems.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, lgtm, size/XL

#197 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, lgtm, size/L

#192 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#198 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#199 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, size/S

#200 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, lgtm, size/L

#201 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, lgtm, size/L

#203 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, lgtm, size/L

#204 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/tracker/enqueue.go
Labels: approved, lgtm, size/M

#206 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, lgtm, size/L

#208 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/.gitignore
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/test/example/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/foo_types.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/test/pub/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/bar_types.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/update-test-codegen.sh
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, lgtm, size/XL

#209 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
Labels: approved, lgtm, size/XXL

#210 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XL

#212 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/apis/testing/conditions.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/apis/testing/v1/conditions.go
  vendor/knative.dev/pkg/apis/testing/v1beta1/conditions.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/webhook/psbinding/contexts.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/types.go
Labels: approved, lgtm, size/L

#213 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
Labels: approved, lgtm, size/L

#214 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/testdata/README.md
Labels: approved, lgtm, size/L

#215 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
Labels: approved, lgtm, size/S
