Repository knative/caching, pull requests merged in 2020-09, with the labels that each got.

#325 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#326 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#327 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#331 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#332 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#334 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#335 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#336 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#338 use v1 CRD APIs
  config/image.yaml
Labels: approved, cla: yes, lgtm, size/S

#341 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#339 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#342 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#343 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#345 The owners was completely out of whack here.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#344 Fix the testing formatting funcs
  pkg/apis/caching/v1alpha1/image_defaults_test.go
  pkg/apis/caching/v1alpha1/image_types_test.go
  pkg/apis/caching/v1alpha1/register_test.go
Labels: approved, cla: yes, lgtm, size/XS
