Repository knative/caching, pull requests merged in 2020-11, with the labels that each got.

#379 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#380 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#381 include an image column
  config/image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#382 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#383 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#384 Fix a few more occurrences of divisive language
  config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#385 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#386 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#387 bump k8s v0.18.12, go1.15
  go.mod
  go.sum
  hack/update-k8s-deps.sh
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#388 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#389 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#391 add dprotaso as an approver
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#390 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#392 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#393 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#394 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#395 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#396 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
