Repository knative/caching, pull requests merged in 2021-08, with the labels that each got.

#505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/caching/v1alpha1/image/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#507 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#508 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#509 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, cla: yes

#512 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/caching/v1alpha1/image/filtered/image.go
  pkg/client/injection/informers/caching/v1alpha1/image/image.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#513 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, cla: yes

#514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/caching/v1alpha1/image/controller.go
  pkg/client/injection/reconciler/caching/v1alpha1/image/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#516 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: lgtm, approved, size/S, cla: yes

#521 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: lgtm, approved, size/S, cla: yes
