Repository knative/caching, pull requests merged in 2021-05, with the labels that each got.

#464 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#466 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#467 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#468 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#470 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#471 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#472 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#475 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#476 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#477 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S
