Repository knative/caching, pull requests merged in 2021-04, with the labels that each got.

#446 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#448 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#447 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#398 Integrate the gopath hacks to allow for codegen anywhere.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, lifecycle/stale, size/S

#450 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#451 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#454 change status to duckv1.status, add reconciler framework
  go.mod
  pkg/apis/caching/v1alpha1/image_lifecycle.go
  pkg/apis/caching/v1alpha1/image_lifecycle_test.go
  pkg/apis/caching/v1alpha1/image_types.go
  pkg/apis/caching/v1alpha1/image_types_test.go
  pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
  pkg/client/injection/reconciler/caching/v1alpha1/image/controller.go
  pkg/client/injection/reconciler/caching/v1alpha1/image/reconciler.go
  pkg/client/injection/reconciler/caching/v1alpha1/image/state.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#455 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#457 Add markready method for image
  pkg/apis/caching/v1alpha1/image_lifecycle.go
  pkg/apis/caching/v1alpha1/image_lifecycle_test.go
  vendor/knative.dev/pkg/apis/testing/conditions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#458 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#459 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/caching/v1alpha1/image/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#460 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/caching/v1alpha1/image/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#462 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
