Repository knative/caching, pull requests merged in 2022-03, with the labels that each got.

#610 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#612 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#614 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#615 Adding code of conduct to reference knative/community's CoC
  code-of-conduct.md
Labels: lgtm, approved, size/M

#616 Remove shortnames for internal resources
  config/image.yaml
Labels: lgtm, approved, size/XS

#617 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL
