Repository knative/caching, pull requests merged in 2025-01, with the labels that each got.

#912 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#913 bump controller-gen to v0.17.0
  config/image.yaml
  hack/update-schemas.sh
Labels: lgtm, approved, size/XS

#916 fix generation of our clientset
  hack/update-codegen.sh
  hack/update-schemas.sh
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/listers/caching/v1alpha1/image.go
Labels: lgtm, approved, size/S

#917 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#918 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#919 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#920 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#921 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/flags/flags.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go111.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go112.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/convert_map.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: lgtm, approved, size/XL
